"""empty message

Revision ID: b98199032fa5
Revises: 3ed67b5b2bec
Create Date: 2024-12-23 00:29:21.498619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98199032fa5'
down_revision: Union[str, None] = '3ed67b5b2bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('t_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('banned', 'chill', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('t_station',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['t_city.city_id'], ),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('t_route',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=False),
    sa.Column('train_no', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['from_station_id'], ['t_station.station_id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['t_station.station_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('t_subscription',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['t_route.route_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'route_id')
    )
    op.create_table('t_ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.Enum('plackart', 'cupe', 'seated', 'sv', name='tickettype'), nullable=False),
    sa.Column('best_price', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['t_route.route_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_ticket')
    op.drop_table('t_subscription')
    op.drop_table('t_route')
    op.drop_table('t_station')
    op.drop_table('t_user')
    op.drop_table('t_city')
    # ### end Alembic commands ###
